namespace: staging

replicaCount: 2

app:
  env: staging

ingress:
  enabled: true
  host: backend-staging.local

resources:
  requests:
    cpu: "150m"
    memory: "192Mi"
  limits:
    cpu: "700m"
    memory: "384Mi"
