namespace: dev

replicaCount: 2

app:
  env: dev

ingress:
  enabled: true
  host: backend-dev.local

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
