namespace: prod

replicaCount: 3

app:
  env: prod

ingress:
  enabled: true
  host: backend-prod.local

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"
